### ISSUE TITLE
issue calculating predKmax

### ISSUE THREAD

**Issue by DeborahMMelo** [renatoamorais/rfishprod#4]
Hello, first of all, I would like to congratulate you on the excellent articles and for making the analyses so accessible. I downloaded the available function to calculate the estimated productivity and tested it with the example provided, but I encountered issues when running the script with my own data. When trying to calculate the 'predKmax', I receive the error: 'Error in predict.xgb.Booster(xgbmod[[i]], newdata = modmatnd): Feature names stored in object and newdata are different!'. Even after selecting only the species in common with the database you created ('db') and adjusting my table, the problem persists. I’m unsure whether what I intend to do can actually be addressed by the script you provided, whether I need to input the data more specifically, or if it would be better to create my own species database with the growth parameters. 
[base_produtividade -exemplo.xlsx](https://github.com/user-attachments/files/18028256/base_produtividade.-exemplo.xlsx)

Thank you in advance for your attention.

**Comment by renatoamorais** [comment]
[predKmax_issue_report.zip](https://github.com/user-attachments/files/18201583/predKmax_issue_report.zip)

Hi Deborah,

Thanks for your words. I'm happy it is helpful! I've done some debugging and the issue is in the data, a couple of mistaken data entries, character vectors where they should be numeric and also NAs. Make sure you're always 100% sure that values in all variables required for prediction match 100% what's required. `tidytrait` does a fair job checking for factor problems, but as your data showed, it doesn't short-circuit things like NAs and wrong values. I'll include more checks in my next update! This solved it all for me (see report attached with the results of the code running), hope it solves for you too.


```{r libr, echo=TRUE, results='hide', warning=FALSE, message=FALSE}

library(readxl)
library(rfishprod)

```

Error while running `predKmax`. First suspicion is always wrong factors or other mistakes in the data. We'll loading OP data and try to debug

```{r loading data}

dt <- read_xlsx('base_produtividade_ex.xlsx')  

```

Function to check values in the factors

```{r fun}

check_vals <- function(data, vars_to_check = c('Diet', 'Position','Method')){
	repdata <- tidytrait(rfishprod:::repdata, dataset = db)
	sapply(vars_to_check, 
	function(x) {
		v1 <- (unlist(unique(data[,x]), use.names=FALSE))
		v2 <- levels(repdata[,x])
		if(all(v1 %in% v2)){
			return('OK')
		} else {
			v1[which(!v1 %in% v2)]
		}
	})
}
```

Checking values
```{r check}
ck <- check_vals(data = dt)
mtk <- ck[ck != 'OK']
```

At least one value does not correspond to factors, correcting it
```{r correct}
dt[dt[, names(mtk)] == mtk, names(mtk)] <- 'BtPlAs'
```

Are sstmean and MaxSizeTL numeric?
```{r numeric}
is.numeric(dt$sstmean)
sapply(c('sstmean','MaxSizeTL'), is.numeric)
```
Neither of them...

Are there NA's?
```{r NA}
apply(dt,2,function(x) any(is.na(x)))
```
Yes, in MaxSizeTL

Fixing both issues
```{r}
dt$sstmean <- as.numeric(dt$sstmean)
dt[is.na(dt$MaxSizeTL),'MaxSizeTL'] <- 70
```


Tidy trait-ing now
```{r tidy}
data <- tidytrait(
	as.data.frame(dt), dataset = db)	
```

Model formula
```{r}
fmod <- formula(~ sstmean + MaxSizeTL + Diet + Position + Method)
```

Running preds with no issues now
```{r}
preds <- predKmax(data, 
                   dataset = db,
                   fmod = fmod,
                   niter = 10,
                   return = 'pred')
```

#### TO DO: add numeric and NA checks to sstmean and MaxSizeTL in `tidytrait`

**Comment by DeborahMMelo** [comment]
Thank you very much for your help!!
